title: my-website
hero_image: images/banner.png
description: my-website description
version: 4
listed: false
copyedit: false
last_tested: "2021-07-14"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
